// File generated by manual configuration for dynetix-mobile
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return const FirebaseOptions(
          apiKey: 'AIzaSyPlaceholderKeyForDynetixMobileAndroid',
          appId: '1:1053444005934:android:placeholder_id',
          messagingSenderId: '1053444005934',
          projectId: 'dynetix-mobile',
          storageBucket: 'dynetix-mobile.appspot.com',
        );
      case TargetPlatform.iOS:
        return const FirebaseOptions(
          apiKey: 'AIzaSyPlaceholderKeyForDynetixMobileIOS',
          appId: '1:1053444005934:ios:placeholder_id',
          messagingSenderId: '1053444005934',
          projectId: 'dynetix-mobile',
          storageBucket: 'dynetix-mobile.appspot.com',
          iosBundleId: 'com.dynetix.app',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia.',
        );
    }
  }
}
