import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/widgets/dynetix_widgets.dart';
import '../../domain/entities/inquiry_entity.dart';
import '../bloc/inquiries_cubit.dart';
import '../bloc/inquiries_state.dart';

class InquiryChatScreen extends StatefulWidget {
  final String itemId;
  final String itemTitle;
  final String userRole; // 'admin' or 'customer'
  final String userId;

  const InquiryChatScreen({
    super.key,
    required this.itemId,
    required this.itemTitle,
    required this.userRole,
    required this.userId,
  });

  @override
  State<InquiryChatScreen> createState() => _InquiryChatScreenState();
}

class _InquiryChatScreenState extends State<InquiryChatScreen> {
  final _messageController = TextEditingController();

  @override
  void initState() {
    super.initState();
    context.read<InquiriesCubit>().watchInquiries(widget.itemId);
  }

  void _sendMessage() {
    if (_messageController.text.trim().isEmpty) return;

    final inquiry = InquiryEntity(
      id: '', // Will be generated by Supabase
      userId: widget.userId,
      itemId: widget.itemId,
      itemType: 'service',
      senderRole: widget.userRole,
      message: _messageController.text.trim(),
      createdAt: DateTime.now(),
    );

    context.read<InquiriesCubit>().sendInquiry(inquiry);
    _messageController.clear();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(widget.itemTitle, style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
            const Text('Dynetix Support • Online', style: TextStyle(fontSize: 10, color: AppColors.success)),
          ],
        ),
        backgroundColor: AppColors.surface,
      ),
      body: Column(
        children: [
          Expanded(
            child: BlocBuilder<InquiriesCubit, InquiriesState>(
              builder: (context, state) {
                if (state is InquiriesLoading) {
                  return const Center(child: CircularProgressIndicator());
                } else if (state is InquiriesLoaded) {
                  final messages = state.inquiries;
                  return ListView.builder(
                    padding: const EdgeInsets.all(20),
                    itemCount: messages.length,
                    itemBuilder: (context, index) {
                      final msg = messages[index];
                      final isMe = msg.senderRole == widget.userRole;

                      return Align(
                        alignment: isMe ? Alignment.centerRight : Alignment.centerLeft,
                        child: Container(
                          margin: const EdgeInsets.only(bottom: 12),
                          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                          constraints: BoxConstraints(maxWidth: MediaQuery.of(context).size.width * 0.75),
                          decoration: BoxDecoration(
                            color: isMe ? AppColors.primary : AppColors.cardBackground,
                            borderRadius: BorderRadius.only(
                              topLeft: const Radius.circular(16),
                              topRight: const Radius.circular(16),
                              bottomLeft: Radius.circular(isMe ? 16 : 0),
                              bottomRight: Radius.circular(isMe ? 0 : 16),
                            ),
                          ),
                          child: Text(
                            msg.message,
                            style: TextStyle(
                              color: isMe ? Colors.black : Colors.white,
                              fontSize: 14,
                            ),
                          ),
                        ),
                      );
                    },
                  );
                } else if (state is InquiriesError) {
                  return Center(child: Text(state.message));
                }
                return const Center(child: Text('Start a conversation', style: TextStyle(color: AppColors.textDisabled)));
              },
            ),
          ),
          _buildInputArea(),
        ],
      ),
    );
  }

  Widget _buildInputArea() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: const BoxDecoration(
        color: AppColors.surface,
        border: Border(top: BorderSide(color: AppColors.glassBorder)),
      ),
      child: SafeArea(
        child: Row(
          children: [
            Expanded(
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                decoration: BoxDecoration(color: Colors.white.withOpacity(0.03), borderRadius: BorderRadius.circular(30)),
                child: TextField(
                  controller: _messageController,
                  style: const TextStyle(color: Colors.white, fontSize: 14),
                  decoration: const InputDecoration(
                    hintText: "Message Support...",
                    border: InputBorder.none,
                    hintStyle: TextStyle(color: AppColors.textDisabled),
                  ),
                ),
              ),
            ),
            const SizedBox(width: 12),
            GestureDetector(
              onTap: _sendMessage,
              child: Container(
                height: 48,
                width: 48,
                decoration: const BoxDecoration(color: AppColors.primary, shape: BoxShape.circle),
                child: const Icon(Icons.send_rounded, color: Colors.black, size: 20),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
